
services : 
  flask : 
    build : 
      context : .
      dockerfile : Dockerfile 
    
    container_name : flask 
    environment : 
      APP_PORT : 5000 
      MONGODB_USERNAME : gaurav 
      MONGODB_PASSWORD : gaurav 

    volumes : 
      - "./:/app" 

    depends_on : 
      - mongo

    ports : 
      - "5000:5000"
  mongo : 
    image : mongo:latest 
    container_name : mongoDB

    environment : 
      MONGO_INITDB_ROOT_USERNAME : gaurav 
      MONGO_INITDB_ROOT_PASSWORD : gaurav
      MONGO_INITDB_DATABASE : userdb 

    volumes : 
      - mongodbdata:/data/db 


  nginx : 
    image : nginx 
    container_name : nginx 
    volumes : 
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports : 
      - "80:80"
    
    depends_on : 
      - flask
volumes : 
  mongodbdata :  
